### ISSUE TITLE
点击超链接后会跳到angular的路由

### ISSUE THREAD

**Issue by avenue2013** [chefomar/angular-scroll-spy#3]
点击超链接后会跳到angular的路由，并触发默认路由！

**Comment by chefomar** [comment]
Hi, would appreciate if you can post in english. 

Either ways, if google translation is correct, your issue is when clicking hyperlink angular will trigger the default router. This is an intended behavior. This library is not made to handle clicking hyperlinks. It is just for spying on HTML elements when scrolling. If you want that behavior you can implement your own.
